**Abstract** 

Cars are being sold more than ever. Many researches have been done in recent years on predicting
used car price with data mining. An accurate used car price
evaluation works as a catalyst in the healthy development of
used car market. Therefore, arises a need for a model that
can assign a price for a vehicle by evaluating its features
taking prices of other cars into consideration. Customers
can be widely exploited by fixing unrealistic prices for the
used cars and many fall into this trap. Therefore, raises an
absolute necessity of a used car price prediction system to
effectively determine the worthiness of the car depending on
a variety of features. This price prediction model bridges
this gap, giving the buyers and sellers an approximate value
of the car using the multiple linear regression to predict the
price.


**INTRODUCTION**


With the increase of car ownership, used car market
shows great potential. An accurate used car price
evaluation is essential for the healthy development of used
car market. The prices of new cars in the industry are fixed
by the manufacturer with some additional costs incurred
by the Government in the form of taxes. But due to the
increased price of new cars and incapability of customers
to buy new cars due to the lack of funds, used cars sales
are on a global increase. Predicting the prices of used cars
is therefore an interesting and much-needed problem that
needs to be addressed.
Given the description of used cars, prediction of used cars
is not an easy task. It is trite knowledge that the value of
used cars depends on various factors

The most important ones are usually the 

 * age of the car
 * its make (and model),
 * the origin of the car (the original country of the manufacturer), 
 * its mileage (the number of kilometers it has run) and 
 * its horsepower. 
 
Due to rising fuel prices, 
 * fuel economy also has a prime importance. 

Some special factors which buyers attach importance is the 
 * local of previous owners, whether the car had been involved in serious accidents and whether it is a lady-driven car. 
 * The look and feel of the car contributes a lot to the price. 
 
 As we can see, the price depends on various different factors. Unfortunately, information about all these factors is not
always available and the buyer must make the decision to purchase at a certain price based on few factors only.

So, we propose a methodology using Machine Learning to predict the prices of used cars given the features. The
price is estimated based on the number of features. We then deploy a responsive website to display our results that consist of all the various listings of used cars. This deployed service is a result of our work, and it incorporates the data, ML model with the features. This methodology can aid in the decision making of the users who are looking to buy a used car. It also provides users with the freedom to search all the available cars at one place without moving, anywhere and at any time.




**EXISTING SYSTEM**

Work on estimating the price of used cars is very recent but also very sparse. The conventional method involves going to a
cars dealer, showing them the documents of the car and then an inspection of the car is performed in order to understand the
state of the build and the engine of the vehicle. Only after such a long procedure and after waiting for around more or less than a week’s time or so, one can expect to get and idea the price range in which the car could be sold.

In the digital world, there have been many different implementations that have been used to effectively predict the
price of a vehicle using different algorithms right from the machine learning algorithms of multiple linear regression, knearest neighbor, naïve bayes to random forest and decision tree to the SAS enterprise miner. In [1], [2], [3], [5] and [7] all these implementations considered different sets of features in order to make their predictions from the historical data that was used to for training the model. 

Here, in addition to not just building a prediction model based on the features that impact the prices the most, we have tried to build a web application where a user will be able to go through listings of the cars that are available for sale, make a decision by checking if the listed prices are on the higher or the lower side and therefore, be able to help the user/customer in the decision making to buy or sell a car, thus giving out a better model replacing the existing ones.

**PROPOSED SYSTEM**


The proposed system provides users with the freedom to search all the available cars at one place without moving,
anywhere and at any time. This methodology can aid in the decision making of the users who are looking to buy a used
car. This enables the people to search for a car without any skepticism of how to make sure if it is a verified seller, how
to contact the seller and to get all the information about the age and build, etc of the car, demonstrating the usefulness,
viability and flexibility of the system. It also aims to ease down the process of finding the right car as per the users’
needs and also shows the car is worth the price listed by the seller.

The basic objective of this system is to let user have a fair idea of what the vehicle could cost them. The system could
also provide the user with a list of choices of different types of cars based on the details of the car the user is looking
for. It helps give the buyer/seller with the substantial information based on which they can take the decision.

The rise of used cars sales is exponentially increasing and the car sellers can take advantage of this scenario by
listing unrealistic prices owing to the demand. Therefore, there arises a need for a model that can assign a price for a
vehicle by evaluating its features taking the prices of other cars into consideration. Our system bridges this gap,
giving the buyers and sellers an approximate value of the car using the best algorithm that can be used to predict the
price.



**IMPLEMENTATION OF SYSTEM:**
    
    
The main page consists of two topics in the navigation bar named ‘Search’ and ‘Predict’. The system lets the user be
able to go through all the records and details of the cars. The main search page includes a table that can be used to
look for a particular car based on the users’ interests. Based on the options selected by the user, the corresponding car records will be fetched from the database and the details of the car will be shown to the user. The user can now check the listed price of the car against the price predicted by the system and make a decision whether to consider buying the car or not. There is also a provision for buyers to post cars for sale.

The ‘Predict’ page consists of a table which asks the user to input the details of the features of the car that will be
used in order to predict an approximate price range for the car. Based on the output of this model, the user will be
able to understand what is the worth of their car and if they would like to sell it. This model has been trained
using historical data that was gathered over a long period of time. Based on the KDD (Knowledge Discovery in Databases) process, the raw data was first collected. It was then preprocessed and was cleaned in order to find useful patterns useful in order to make some meaning out of those patterns. This data was then used to train the model using Multiple Linear Regression in Python. The current count of our training dataset is around 1700-1750 based on which the price is being predicted.
Based on the details the user inputs, the underlying system predicts the price based on the values of the inputs passed to it. 

**APPLICATIONS:**
    
    
The basic objective of this system is to let user have a fair idea of what the vehicle could cost them. The website could also provide the user with a list of choices of different types of cars based on the details of the car the user is looking for. It helps give the buyer/seller with the substantial information based on which they can take the decision. In addition, following are a few other applications:

* On-road price: User can get an approximate on-road price of any model for any city, on one’s fingertips
* Compare cars- Decide on the go: User will not have to wait for long time! They will be able to easily   choose their favorite   cars against different models with our prediction tool on our website
* Sell cars- Post for resale: Seller will be able to post their car for sale once they are satisfied with the price.
* Buy cars: Since the price of the car is predicted by the model using large amount of data, there are less chances of any     unrealistic pricing.
* Analytics: The user can understand the trends in the variation of the car prices with respect to age, usage of the car to better understand the how prices are influenced based on these factors.
* 

**FUTURE SCOPE:**

Given the current working and design of the proposed systems, there is definitely a place for future enhancements. As better and more reliable technology comes ahead of us, more features can be added by providing a better experience by adding provisions for electric cars when the technology will be used by the public in large numbers. In addition to this, various different variations in cars such as the hybrid engines can be introduced. With future generations of the product, modules such as the comparison and payment gateways can be implemented into the system, leading towards development of a proper business model which can then be used by businesses along with refined and interactive analytics that can be used to understand the trends in the prices and different automobile types.

Lastly, enhancements in the machine learning algorithms used can help increase the accuracy of the system and
therefore can help towards the research and development of the topic

**CONCLUSION:**
    
    
With the increase of car ownership, used car market shows great potential. An accurate used car price evaluation is
essential for the healthy development of used car market. The automobile resale system would prove useful in helping the potential car buyers to find the best car for their budget and at the same time give a predicted price for the car one intends to sell, thereby proving to be a very useful tool helping people facilitate finding the best deal for their budget which is a very popular and trending niche in the used cars market.

The overall system being real-time and interactive with the user helps it to be an overall innovative proposed idea
which can be easily implemented providing an overall satisfaction to the customer proving to become a successful business idea.

In [39]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
estimator = SVR(kernel="linear", C=100)
selector = RFE(estimator, 5, step=1)
selector = selector.fit(X, y)
selector.support_

array([ True,  True, False,  True,  True,  True, False, False, False,
       False])

In [40]:
selector.score(X,y)

0.7543626878877557

In [41]:
selector.support_ 

array([ True,  True, False,  True,  True,  True, False, False, False,
       False])

In [42]:
selector.ranking_

array([1, 1, 3, 1, 1, 1, 4, 2, 5, 6])

In [43]:
print(selector.n_features_)

5


In [44]:
# # Spliting into 80% for training set and 20% for testing set so we can see our accuracy
# X_train, x_test, Y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [60]:
import numpy as np
import pandas as pd

In [85]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X, Y = make_friedman1(n_samples=50, n_features=10, random_state=0)

In [86]:
# X = pd.DataFrame(X)
# X.head()

In [87]:
# Y = Y.reshape(-1, 1)
# Y

In [88]:
X_train, x_test, Y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [89]:
reg = LinearRegression()
reg.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [90]:
reg.score(X_train, Y_train)

0.8148517351920732

In [101]:
reg_pred = reg.predict(x_test)

In [102]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, reg_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, reg_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, reg_pred)))

Mean Absolute Error: 2.7363620172062744
Mean Squared Error: 11.678479927247347
Root Mean Squared Error: 3.417379102067452


In [92]:
reg.get_params

<bound method BaseEstimator.get_params of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)>

In [93]:
from sklearn.feature_selection import RFE

estimator = LinearRegression()
selector = RFE(estimator, n_features_to_select=5, step=1)
selector = selector.fit(X, Y)

In [100]:
selector.score(X,Y)

0.7803347654150063

In [94]:
selector.support_

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [98]:
print([selector.support_])

[array([ True,  True,  True,  True,  True, False, False, False, False,
       False])]


In [99]:
selector.ranking_

array([1, 1, 1, 1, 1, 2, 3, 6, 5, 4])